[project]
site_name = "读书笔记"
site_description = "书籍是与大师对话的最好方式"
site_author = "Palemoky"
site_url = "https://readings.palemoky.com"
repo_url = "https://github.com/palemoky"
repo_name = "palemoky"
copyright = "Copyright © 2026 Palemoky"
extra_javascript = [
  "assets/javascripts/mathjax.js",
  "https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js",
]
extra_css = [
  "assets/stylesheets/extra.css",
]
nav = [
  { "首页" = "index.md" },
  { "操作系统" = ["csapp/README.md", "ddia/README.md"] },
  { "数据库" = ["mysql/README.md", "redis/README.md"] },
  { "网络" = ["tcp-ip/README.md"] },
]

[project.theme]
variant = "modern"
language = "zh"
primary = "white"
accent = "blue"
favicon = "assets/logo.png"
logo = "assets/logo.png"
features = [
  "announce.dismiss",
  "content.action.edit",
  "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.tooltips",
  "navigation.expand",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.progress",
  "navigation.path",
  "navigation.sections",
  "navigation.tabs",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "search.share",
  "search.suggest",
  "toc.follow",
]

palette = [
  { scheme = "default", toggle.icon = "lucide/sun", toggle.name = "Switch to dark mode" },
  { scheme = "slate", toggle.icon = "lucide/moon", toggle.name = "Switch to light mode" },
]
icon.repo = "fontawesome/brands/github"
icon.edit = "lucide/file-edit"

[project.extra]
generator = false
social = [
  { icon = "fontawesome/brands/github", link = "https://github.com/palemoky" },
]
