[project]
site_name = "读书笔记"
site_description = "书籍是与大师对话的最好方式"
site_author = "Palemoky"
site_url = "https://readings.palemoky.com"
repo_url = "https://github.com/palemoky"
repo_name = "palemoky"
copyright = "Copyright © 2026 Palemoky"
extra_javascript = [
  "assets/javascripts/mathjax.js",
  "https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js",
]
extra_css = [
  "assets/stylesheets/extra.css",
]
nav = [
  { "首页" = "index.md" },
  { "计算机系统" = [
    {"深入理解计算机系统" = "csapp/README.md"}, 
    {"深入理解数据结构与算法" = "ddia/README.md"}, 
    {"操作系统导论" = "ostep/README.md"}, 
    {"Linux UNIX 系统编程" = "linux-unix-system-programming/README.md"}, 
    {"系统性能" = "systems-performance/README.md"}, 
    {"代码大全" = "code/README.md"}
  ] },
  { "网络通信" = [
    {"TCP/IP" = "tcp-ip/README.md"}, 
    {"HTTP 完全指南" = "http-the-definitive-guide/README.md"}, 
    {"网络是如何工作的" = "how-networks-work/README.md"}, 
    {"TCP/IP 卷 1" = "tcp-ip-vol1/README.md"}
  ] },
  { "数据库" = [
    {"MySQL" = "mysql/README.md"}, 
    {"Redis" = "redis/README.md"}, 
    {"高性能 MySQL" = "high-performance-mysql/README.md"}, 
    {"Redis DevOps" = "redis-dev-ops/README.md"}
  ] },
  { "软件工程" = [
    {"代码大全" = "code-complete/README.md"}, 
    {"精通正则表达式" = "mastering-regular-expressions/README.md"}
  ] },
  { "安全与加密" = [
    {"密码学" = "cryptography/README.md"}
  ] },
  { "区块链" = [
    {"精通以太坊" = "mastering-ethereum/README.md"}
  ] },
  { "社会人文" = [
    {"人类简史" = "sapiens/README.md"}
  ] },
]

[project.theme]
variant = "modern"
language = "zh"
primary = "white"
accent = "blue"
favicon = "assets/logo.png"
logo = "assets/logo.png"
features = [
  "announce.dismiss",
  "content.action.edit",
  "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.tooltips",
  "navigation.expand",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.progress",
  "navigation.path",
  "navigation.sections",
  "navigation.tabs",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "search.share",
  "search.suggest",
  "toc.follow",
]

palette = [
  { scheme = "default", toggle.icon = "lucide/sun", toggle.name = "Switch to dark mode" },
  { scheme = "slate", toggle.icon = "lucide/moon", toggle.name = "Switch to light mode" },
]
icon.repo = "fontawesome/brands/github"
icon.edit = "lucide/file-edit"

[project.extra]
generator = false
social = [
  { icon = "fontawesome/brands/github", link = "https://github.com/palemoky" },
]
