[project]
site_name = "藏经阁"
site_description = "书籍是与大师对话的最好方式"
site_author = "Palemoky"
site_url = "https://readings.palemoky.com"
repo_url = "https://github.com/palemoky/readings"
repo_name = "palemoky"
copyright = "Copyright &copy; <span id='copyright-year'>2026</span> Palemoky"
extra_javascript = [
  "assets/javascripts/mathjax.js",
  "https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js",
  "assets/javascripts/width-toggle.js",
]
extra_css = [
  "assets/stylesheets/extra.css",
]
nav = [
  { "首页" = "index.md" },
  { "计算机系统" = [
    {"计算机系统" = "os/README.md"}, 
    {"深入理解计算机系统" = "os/csapp/README.md"}, 
    {"操作系统导论" = "os/ostep/README.md"}, 
    {"Linux/Unix 系统编程" = "os/linux-unix-system-programming/README.md"}, 
    {"性能之巅" = "os/systems-performance/README.md"}, 
  ] },
  { "网络通信" = [
    {"网络通信" = "network/README.md"}, 
    {"HTTP 权威指南" = "network/http-the-definitive-guide/README.md"}, 
    {"网络是怎样连接的" = "network/how-networks-work/README.md"}, 
    {"TCP/IP 详解（卷1）" = "network/tcp-ip-vol1/README.md"}
  ] },
  { "数据库" = [
    {"数据库" = "database/README.md"}, 
    {"高性能 MySQL" = "database/high-performance-mysql/README.md"}, 
    {"Redis 开发与运维" = "database/redis-dev-ops/README.md"}
  ] },
  { "分布式" = [
    {"分布式" = "distributed/README.md"}, 
    {"数据密集型应用设计" = "distributed/ddia/README.md"},
    # {"Kubernetes 权威指南" = "distributed/kubernetes-the-definitive-guide/README.md"}
  ] },
  { "软件工程" = [
    {"软件工程" = "software/README.md"},
    {"编码" = "software/code/README.md"},
    {"代码大全" = "software/code-complete/README.md"}, 
    {"精通正则表达式" = "software/mastering-regular-expressions/README.md"}
  ] },
  { "安全与加密" = [
    {"安全与加密" = "crypto/README.md"},
    {"图解密码技术" = "crypto/cryptography/README.md"}
  ] },
  { "区块链" = [
    {"区块链" = "blockchain/README.md"},
    {"精通以太坊" = "blockchain/mastering-ethereum/README.md"}
  ] },
  { "其他" = [
    {"其他" = "others/README.md"},
    {"人类简史" = "others/sapiens/README.md"}
  ] },
]

[project.theme]
variant = "modern"
language = "zh"
primary = "white"
accent = "blue"
custom_dir = "overrides"
favicon = "assets/logo.png"
logo = "assets/logo.png"
features = [
  "announce.dismiss",
  "content.action.edit",
  "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.tooltips",
  "navigation.expand",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.progress",
  "navigation.path",
  "navigation.sections",
  "navigation.tabs",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "search.share",
  "search.suggest",
  "toc.follow",
]

icon = { repo = "fontawesome/brands/github", edit = "lucide/file-edit" }
palette = [
  { scheme = "default", toggle.icon = "lucide/sun", toggle.name = "Switch to dark mode" },
  { scheme = "slate", toggle.icon = "lucide/moon", toggle.name = "Switch to light mode" },
]

[project.markdown_extensions]
attr_list = {}
md_in_html = {}
admonition = {}
footnotes = {}
abbr = {}
def_list = {}
toc.permalink = true
toc.slugify = { object = "pymdownx.slugs.slugify", kwds = { case = "lower" } }

[project.markdown_extensions.pymdownx]
arithmatex = { generic = true }
betterem = { smart_enable = "none" }
caret = {}
details = {}
emoji = { emoji_generator = "zensical.extensions.emoji.to_svg", emoji_index = "zensical.extensions.emoji.twemoji" }
highlight.pygments_lang_class = true
inlinehilite = {}
keys = {}
mark = {}
smartsymbols = {}
superfences = {}
tabbed = { alternate_style = true }
tasklist = { custom_checkbox = true }
tilde = {}
magiclink = {}
blocks.caption = {}

[project.extra]
generator = false
social = [
  { icon = "fontawesome/brands/github", link = "https://github.com/palemoky" },
  { icon = "fontawesome/solid/brain", link = "https://algo.palemoky.com" },
  # { icon = "fontawesome/solid/feather-pointed", link = "https://blog.palemoky.com" }
]
